apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: istio-system
  namespace: istio-system
resources:
- ns.yaml
- base.manifest.k-flux.yaml

- manifest.k-flux.yaml
# - telemetry.yaml

