apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-mixer
  namespace: istio-system
spec:
  dependsOn:
  - name: istio-base
    namespace: istio-system
  interval: 10m
  path: ./infrastructure/istio-system/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
