apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: sonarqube
  namespace: flux-manifests
spec:
  interval: 15m0s
  url: https://SonarSource.github.io/helm-chart-sonarqube
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: longhorn
  namespace: flux-manifests
spec:
  interval: 15m0s
  url: https://charts.longhorn.io
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: istio
  namespace: flux-manifests
spec:
  interval: 15m
  url: https://istio-release.storage.googleapis.com/charts

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-manifests
spec:
  interval: 15m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-manifests
spec:
  interval: 15m
  url: https://grafana.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: hivemq
  namespace: flux-manifests
spec:
  interval: 15m
  url: https://hivemq.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: mqtt
  namespace: flux-manifests
spec:
  interval: 15m
  url: https://k8s-at-home.com/charts/
---

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: t3n
  namespace: flux-manifests
spec:
  interval: 15m
  url: https://storage.googleapis.com/t3n-helm-charts
---


apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: basic-charts
  namespace: flux-manifests
spec:
  interval: 15m
  url: https://csberger.github.io/basic_charts/charts/
---

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cluster-autoscaler
  namespace: flux-manifests
spec:
  interval: 15m
  url: https://kubernetes.github.io/autoscaler
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: flux-manifests
spec:
  interval: 15m
  url: https://charts.external-secrets.io
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: flagger
  namespace: flux-manifests
spec:
  interval: 15m
  url: https://flagger.app
