apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-credentials
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: grafana-credentials
    creationPolicy: Owner
  data:
  - secretKey: adminUsername
    remoteRef:
      key: "secretstore/monitoring_credentials"
      property: username
  - secretKey: adminPassword
    remoteRef:
      key: "secretstore/monitoring_credentials"
      property: password
