apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ilant-credentials
  namespace: ilant
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: ilant-apikey
    creationPolicy: Owner
  data:
  - secretKey: api_key
    remoteRef:
      key: "secretstore/ilant_api_key"
      property: api_key
