apiVersion: v1
kind: Service
metadata:
  name: ilant-be
  namespace: ilant
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: ilant-be
  type: ClusterIP

