apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 5m
  chart:
    spec:
      chart: external-secrets
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-manifests
      interval: 1m
  values:
    installCRDs: false  
    tolerations:
    - key: "dedicated"
      operator: Exists
    nodeSelector:
      role: system
  